spring:
  datasource:
    url: jdbc:mysql://sehwan24.cfj6xtfovmom.ap-northeast-2.rds.amazonaws.com:3306/EatToday
    username: sehwan24
    password: "**Se1224"
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    include: real-db

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
      defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind:

# 랜덤 비밀 키 발급 받음
jwt:
  secret: 0bd23166f2fd39744aeb25531eb77155290c53e5c44c4f3d872bb93cf5062c8260a3da93d1d9894dd1ee4a3e33053104a6ecbf4fbccc9cc73c2729d30ad886e9